import type { ResourceConfig } from "./types";

export const DEBUGGING_CONFIGS = {
  checkout_sessions: {
    key: "checkout_sessions", label: "Checkout sessions", labelSingular: "checkout session",
    description: "Inspect checkout sessions and edit diagnostic notes.",
    primaryKey: "id", defaultOrder: "created_at", defaultDescending: true,
    listDisplay: [
      { name: "customer_email_snapshot", label: "Customer email snapshot", kind: "text", sortable: true },
      { name: "provider_payment_id", label: "Provider payment id", kind: "text", sortable: true },
      { name: "status", label: "Status", kind: "status", sortable: true },
      { name: "last_error", label: "Last error", kind: "text", sortable: true },
      { name: "created_at", label: "Created at", kind: "date", sortable: true },
    ],
    fields: [
      { name: "last_error", label: "Last error", kind: "textarea", nullable: true },
    ],
    searchFields: [{ label: "Customer email snapshot", value: "customer_email_snapshot" }, { label: "Provider payment id", value: "provider_payment_id" }, { label: "Last error", value: "last_error" }],
    filters: [{ name: "status", label: "Status" }],
    mutations: { basePath: "/debugging/checkout_sessions" },
    canCreate: false, canEdit: true, canDelete: false, canBulkDelete: false,
  },
  checkout_invites: {
    key: "checkout_invites", label: "Checkout invites", labelSingular: "checkout invite",
    description: "Inspect checkout invites and edit diagnostic notes.",
    primaryKey: "id", defaultOrder: "created_at", defaultDescending: true,
    listDisplay: [
      { name: "label", label: "Label", kind: "text", sortable: true },
      { name: "plan_id", label: "Plan id", kind: "text", sortable: true },
      { name: "expires_at", label: "Expires at", kind: "date", sortable: true },
      { name: "revoked_at", label: "Revoked at", kind: "date", sortable: true },
      { name: "created_at", label: "Created at", kind: "date", sortable: true },
    ],
    fields: [
      { name: "label", label: "Label", kind: "textarea", nullable: true },
    ],
    searchFields: [{ label: "Label", value: "label" }],
    filters: [],
    mutations: { basePath: "/debugging/checkout_invites" },
    canCreate: false, canEdit: true, canDelete: false, canBulkDelete: false,
  },
  webhook_events: {
    key: "webhook_events", label: "Payment webhooks", labelSingular: "payment webhook",
    description: "Inspect payment webhooks and edit diagnostic notes.",
    primaryKey: "id", defaultOrder: "received_at", defaultDescending: true,
    listDisplay: [
      { name: "provider", label: "Provider", kind: "text", sortable: true },
      { name: "event_type", label: "Event type", kind: "text", sortable: true },
      { name: "status", label: "Status", kind: "status", sortable: true },
      { name: "processing_attempts", label: "Processing attempts", kind: "number", sortable: true },
      { name: "last_error", label: "Last error", kind: "text", sortable: true },
      { name: "received_at", label: "Received at", kind: "date", sortable: true },
    ],
    fields: [
      { name: "last_error", label: "Last error", kind: "textarea", nullable: true },
    ],
    searchFields: [{ label: "Provider", value: "provider" }, { label: "Event type", value: "event_type" }, { label: "Last error", value: "last_error" }],
    filters: [{ name: "status", label: "Status" }],
    mutations: { basePath: "/debugging/webhook_events" },
    canCreate: false, canEdit: true, canDelete: false, canBulkDelete: false,
  },
  affiliate_commissions: {
    key: "affiliate_commissions", label: "Affiliate commissions", labelSingular: "affiliate commission",
    description: "Inspect affiliate commissions and edit diagnostic notes.",
    primaryKey: "id", defaultOrder: "created_at", defaultDescending: true,
    listDisplay: [
      { name: "affiliate_user_id", label: "Affiliate user id", kind: "text", sortable: true },
      { name: "amount_minor", label: "Amount minor", kind: "number", sortable: true },
      { name: "currency", label: "Currency", kind: "text", sortable: true },
      { name: "status", label: "Status", kind: "status", sortable: true },
      { name: "description", label: "Description", kind: "text", sortable: true },
      { name: "created_at", label: "Created at", kind: "date", sortable: true },
    ],
    fields: [
      { name: "description", label: "Description", kind: "textarea", nullable: true },
    ],
    searchFields: [{ label: "Description", value: "description" }],
    filters: [{ name: "affiliate_user_id", label: "Affiliate user id" }, { name: "status", label: "Status" }],
    mutations: { basePath: "/debugging/affiliate_commissions" },
    canCreate: false, canEdit: true, canDelete: false, canBulkDelete: false,
  },
  affiliate_withdrawals: {
    key: "affiliate_withdrawals", label: "Affiliate withdrawals", labelSingular: "affiliate withdrawal",
    description: "Inspect affiliate withdrawals and edit diagnostic notes.",
    primaryKey: "id", defaultOrder: "requested_at", defaultDescending: true,
    listDisplay: [
      { name: "affiliate_user_id", label: "Affiliate user id", kind: "text", sortable: true },
      { name: "amount_minor", label: "Amount minor", kind: "number", sortable: true },
      { name: "currency", label: "Currency", kind: "text", sortable: true },
      { name: "status", label: "Status", kind: "status", sortable: true },
      { name: "admin_notes", label: "Admin notes", kind: "text", sortable: true },
      { name: "requested_at", label: "Requested at", kind: "date", sortable: true },
    ],
    fields: [
      { name: "admin_notes", label: "Admin notes", kind: "textarea", nullable: true },
    ],
    searchFields: [{ label: "Admin notes", value: "admin_notes" }],
    filters: [{ name: "affiliate_user_id", label: "Affiliate user id" }, { name: "status", label: "Status" }],
    mutations: { basePath: "/debugging/affiliate_withdrawals" },
    canCreate: false, canEdit: true, canDelete: false, canBulkDelete: false,
  },
  generation_attempts: {
    key: "generation_attempts", label: "Job attempts", labelSingular: "job attempt",
    description: "Inspect job attempts and edit diagnostic notes.",
    primaryKey: "id", defaultOrder: "created_at", defaultDescending: true,
    listDisplay: [
      { name: "generation_id", label: "Generation id", kind: "text", sortable: true },
      { name: "external_job_id", label: "External job id", kind: "text", sortable: true },
      { name: "status", label: "Status", kind: "status", sortable: true },
      { name: "progress", label: "Progress", kind: "number", sortable: true },
      { name: "error_message", label: "Error message", kind: "text", sortable: true },
      { name: "created_at", label: "Created at", kind: "date", sortable: true },
    ],
    fields: [
      { name: "error_code", label: "Error code", kind: "textarea", nullable: true },
      { name: "error_message", label: "Error message", kind: "textarea", nullable: true },
    ],
    searchFields: [{ label: "External job id", value: "external_job_id" }, { label: "Error message", value: "error_message" }],
    filters: [{ name: "generation_id", label: "Generation id" }, { name: "status", label: "Status" }],
    mutations: { basePath: "/debugging/generation_attempts" },
    canCreate: false, canEdit: true, canDelete: false, canBulkDelete: false,
  },
  generation_outbox: {
    key: "generation_outbox", label: "Job outbox", labelSingular: "job outbox entry",
    description: "Inspect job outbox and edit diagnostic notes.",
    primaryKey: "id", defaultOrder: "created_at", defaultDescending: true,
    listDisplay: [
      { name: "generation_id", label: "Generation id", kind: "text", sortable: true },
      { name: "event_type", label: "Event type", kind: "text", sortable: true },
      { name: "delivery_count", label: "Delivery count", kind: "number", sortable: true },
      { name: "delivered_at", label: "Delivered at", kind: "date", sortable: true },
      { name: "last_error", label: "Last error", kind: "text", sortable: true },
      { name: "created_at", label: "Created at", kind: "date", sortable: true },
    ],
    fields: [
      { name: "last_error", label: "Last error", kind: "textarea", nullable: true },
    ],
    searchFields: [{ label: "Event type", value: "event_type" }, { label: "Last error", value: "last_error" }],
    filters: [{ name: "generation_id", label: "Generation id" }],
    mutations: { basePath: "/debugging/generation_outbox" },
    canCreate: false, canEdit: true, canDelete: false, canBulkDelete: false,
  },
} satisfies Record<string, ResourceConfig>;
