import { DEBUGGING_CONFIGS } from "./debugging-resources";
import { CATALOG_CONFIGS } from "./catalog-resources";
import { SUBSCRIPTION_CONFIG } from "./subscription-resource";
import type {
  ResourceConfig,
  ResourceKey,
  SelectOption,
} from "./types";

const PLAN_OPTIONS: SelectOption[] = [
  { label: "Free", value: "free" },
  { label: "Trial", value: "trial" },
  { label: "Pro", value: "pro" },
  { label: "Creator", value: "pro_plus" },
  { label: "Business", value: "business" },
  { label: "Starter", value: "starter" },
  { label: "Scale", value: "scale" },
];

const GENERATION_TYPE_OPTIONS: SelectOption[] = [
  { label: "Image", value: "image" },
  { label: "Text to speech", value: "tts" },
  { label: "Video", value: "video" },
          { label: "Image to image", value: "image2image" },
];

export const RESOURCE_CONFIGS: Record<ResourceKey, ResourceConfig> = {
  ...CATALOG_CONFIGS,
  ...DEBUGGING_CONFIGS,
  entitlements: SUBSCRIPTION_CONFIG,
  users: {
    key: "users",
    label: "Users",
    labelSingular: "user",
    description: "Accounts, assigned plans, and administrator access.",
    primaryKey: "id",
    defaultOrder: "created_at",
    defaultDescending: true,
    listDisplay: [
      { name: "email", label: "Email", sortable: true },
      { name: "name", label: "Name", sortable: true },
      { name: "plan", label: "Plan", kind: "status", sortable: true },
      { name: "is_superuser", label: "Superuser", kind: "boolean", sortable: true },
      { name: "is_suspended", label: "Suspended", kind: "boolean", sortable: true },
      { name: "is_comped", label: "Comped", kind: "boolean", sortable: true },
      { name: "created_at", label: "Created", kind: "date", sortable: true },
    ],
    fields: [
      { name: "email", label: "Email", kind: "email", required: true },
      {
        name: "password",
        label: "Password",
        kind: "password",
        required: true,
        createOnly: true,
        minLength: 8,
        maxLength: 1024,
        help: "Use at least 8 characters. Share this password with the user so they can sign in. No email is sent automatically.",
      },
      {
        name: "password_confirmation",
        label: "Confirm password",
        kind: "password",
        required: true,
        createOnly: true,
        minLength: 8,
        maxLength: 1024,
        confirms: "password",
      },
      { name: "name", label: "Name", kind: "text", nullable: true },
      { name: "avatar_url", label: "Avatar URL", kind: "text", nullable: true },
      {
        name: "plan",
        label: "Plan",
        kind: "relation",
        referenceResource: "plans",
        referenceValue: "code",
        defaultValue: "free",
      },
      {
        name: "is_superuser",
        label: "Superuser",
        kind: "boolean",
        defaultValue: false,
        help: "Allows this active user to sign in to administration and manage the system.",
      },
      {
        name: "is_comped",
        label: "Comped (non-paying)",
        kind: "boolean",
        defaultValue: false,
        help: "Required when an admin assigns a paid plan without a billing subscription.",
      },
      {
        name: "is_suspended",
        label: "Suspended",
        kind: "boolean",
        defaultValue: false,
      },
      {
        name: "referred_by",
        label: "Referral code",
        kind: "text",
        nullable: true,
      },
    ],
    searchFields: [
      { label: "Email", value: "email" },
      { label: "Name", value: "name" },
      { label: "WorkOS ID", value: "workos_id" },
    ],
    filters: [
      { name: "plan", label: "Plan", options: PLAN_OPTIONS },
      {
        name: "is_suspended",
        label: "Suspended",
        options: [
          { label: "Yes", value: "true" },
          { label: "No", value: "false" },
        ],
      },
      {
        name: "is_comped",
        label: "Comped",
        options: [
          { label: "Yes", value: "true" },
          { label: "No", value: "false" },
        ],
      },
    ],
    mutations: { basePath: "/users" },
    canCreate: true,
    canEdit: true,
    canDelete: true,
    canBulkDelete: false,
  },
  api_keys: {
    key: "api_keys",
    label: "API keys",
    labelSingular: "API key",
    description: "Issue, rename, revoke, and audit API credentials. Each key is bound to one product.",
    primaryKey: "id",
    defaultOrder: "created_at",
    defaultDescending: true,
    listDisplay: [
      { name: "key_hint", label: "Key", kind: "identifier", sortable: true },
      { name: "name", label: "Name", sortable: true },
      {
        name: "user_id",
        label: "User",
        display: {
          primaryPath: "user.name",
          secondaryPath: "user.email",
          fallbackPaths: ["user.email", "user_id"],
        },
      },
      { name: "type", label: "Type", kind: "status", sortable: true },
      { name: "is_active", label: "Active", kind: "boolean", sortable: true },
      { name: "last_used_at", label: "Last used", kind: "date", sortable: true },
      { name: "created_at", label: "Created", kind: "date", sortable: true },
    ],
    fields: [
      {
        name: "user_id",
        label: "User ID",
        kind: "text",
        required: true,
        createOnly: true,
        immutableOnEdit: true,
      },
      { name: "name", label: "Name", kind: "text", defaultValue: "Default Key" },
      {
        name: "type",
        label: "Type",
        kind: "select",
        required: true,
        immutableOnEdit: true,
        options: [
          { label: "Image generation", value: "image" },
          { label: "Text to speech", value: "tts" },
          { label: "Video", value: "video" },
          { label: "Image to image", value: "image2image" },
        ],
        defaultValue: "image",
      },
      {
        name: "is_active",
        label: "Active",
        kind: "boolean",
        editOnly: true,
        defaultValue: true,
      },
    ],
    searchFields: [
      { label: "Key hint", value: "key_hint" },
      { label: "Name", value: "name" },
      { label: "Type", value: "type" },
    ],
    filters: [
      {
        name: "type",
        label: "Type",
        options: [
          { label: "Image generation", value: "image" },
          { label: "Text to speech", value: "tts" },
          { label: "Video", value: "video" },
          { label: "Image to image", value: "image2image" },
        ],
      },
      {
        name: "is_active",
        label: "Active",
        options: [
          { label: "Yes", value: "true" },
          { label: "No", value: "false" },
        ],
      },
    ],
    mutations: { basePath: "/api-keys" },
    canCreate: true,
    canEdit: true,
    canDelete: true,
    canBulkDelete: false,
    secretResponseFields: ["raw_key", "full_key"],
  },
  security_blocklist: {
    key: "security_blocklist",
    label: "Security blocklist",
    labelSingular: "blocklist entry",
    description: "Denied IP addresses, CIDR ranges, and disposable email domains.",
    primaryKey: "id",
    defaultOrder: "created_at",
    defaultDescending: true,
    listDisplay: [
      { name: "type", label: "Type", kind: "status", sortable: true },
      { name: "value", label: "Value", kind: "identifier", sortable: true },
      { name: "reason", label: "Reason", sortable: true },
      { name: "created_by", label: "Created by", sortable: true },
      { name: "created_at", label: "Created", kind: "date", sortable: true },
    ],
    fields: [
      {
        name: "type",
        label: "Type",
        kind: "select",
        required: true,
        options: [
          { label: "IP address", value: "ip" },
          { label: "Email domain", value: "email_domain" },
        ],
        defaultValue: "ip",
        help: "Use IP for both individual IP addresses and CIDR ranges; the backend detects CIDR notation.",
      },
      { name: "value", label: "Value", kind: "text", required: true },
      { name: "reason", label: "Reason", kind: "textarea", nullable: true },
    ],
    searchFields: [
      { label: "Value", value: "value" },
      { label: "Reason", value: "reason" },
      { label: "Type", value: "type" },
    ],
    filters: [
      {
        name: "type",
        label: "Type",
        options: [
          { label: "IP address", value: "ip" },
          { label: "Email domain", value: "email_domain" },
        ],
      },
    ],
    mutations: { basePath: "/blocklist" },
    canCreate: true,
    canEdit: true,
    canDelete: true,
    canBulkDelete: true,
  },
  meta_deletion_requests: {
    key: "meta_deletion_requests",
    label: "Meta deletion requests",
    labelSingular: "Meta deletion request",
    description: "Track and resolve Meta data-deletion callbacks.",
    primaryKey: "id",
    defaultOrder: "requested_at",
    defaultDescending: true,
    listDisplay: [
      { name: "confirmation_code", label: "Confirmation", kind: "identifier", sortable: true },
      { name: "status", label: "Status", kind: "status", sortable: true },
      { name: "requested_at", label: "Requested", kind: "date", sortable: true },
      { name: "completed_at", label: "Completed", kind: "date", sortable: true },
      { name: "error", label: "Error", sortable: true },
    ],
    fields: [
      {
        name: "meta_user_id",
        label: "Meta user ID",
        kind: "text",
        required: true,
        createOnly: true,
        help: "Stored securely and intentionally omitted from table reads.",
      },
      {
        name: "confirmation_code",
        label: "Confirmation code",
        kind: "text",
        nullable: true,
        createOnly: true,
        help: "Leave empty to generate a code on the server.",
      },
      {
        name: "status",
        label: "Status",
        kind: "select",
        required: true,
        options: [
          { label: "Pending", value: "pending" },
          { label: "Processing", value: "processing" },
          { label: "Completed", value: "completed" },
          { label: "Failed", value: "failed" },
        ],
        defaultValue: "pending",
      },
      { name: "completed_at", label: "Completed at", kind: "datetime", nullable: true, editOnly: true },
      { name: "error", label: "Error", kind: "textarea", nullable: true, editOnly: true },
    ],
    searchFields: [
      { label: "Confirmation code", value: "confirmation_code" },
      { label: "Status", value: "status" },
    ],
    filters: [
      {
        name: "status",
        label: "Status",
        options: [
          { label: "Pending", value: "pending" },
          { label: "Processing", value: "processing" },
          { label: "Completed", value: "completed" },
          { label: "Failed", value: "failed" },
        ],
      },
    ],
    mutations: { basePath: "/meta-deletion-requests" },
    canCreate: true,
    canEdit: true,
    canDelete: true,
    canBulkDelete: false,
  },
  newsletter_subscribers: {
    key: "newsletter_subscribers",
    label: "Newsletter subscribers",
    labelSingular: "newsletter subscriber",
    description: "Email subscriptions and their acquisition source.",
    primaryKey: "id",
    defaultOrder: "created_at",
    defaultDescending: true,
    listDisplay: [
      { name: "email", label: "Email", sortable: true },
      { name: "source", label: "Source", kind: "status", sortable: true },
      { name: "created_at", label: "Subscribed", kind: "date", sortable: true },
    ],
    fields: [
      { name: "email", label: "Email", kind: "email", required: true },
      { name: "source", label: "Source", kind: "text", required: true, defaultValue: "admin" },
    ],
    searchFields: [
      { label: "Email", value: "email" },
      { label: "Source", value: "source" },
    ],
    filters: [{ name: "source", label: "Source" }],
    mutations: { basePath: "/newsletter-subscribers" },
    canCreate: true,
    canEdit: true,
    canDelete: true,
    canBulkDelete: true,
  },
  affiliates: {
    key: "affiliates",
    label: "Affiliates",
    labelSingular: "affiliate",
    description: "Referral partners, contact details, and available wallet balance.",
    primaryKey: "id",
    defaultOrder: "created_at",
    defaultDescending: true,
    listDisplay: [
      { name: "email", label: "Email", sortable: true },
      { name: "name", label: "Name", sortable: true },
      { name: "created_at", label: "Joined", kind: "date", sortable: true },
    ],
    fields: [
      { name: "email", label: "Email", kind: "email", required: true },
      { name: "name", label: "Name", kind: "text", nullable: true },
      {
        name: "wallet_balance",
        label: "Wallet balance (USD)",
        kind: "number",
        min: 0,
        step: 0.01,
        defaultValue: 0,
        help: "Manual changes affect the payout balance; verify them against the commission ledger.",
      },
    ],
    searchFields: [
      { label: "Email", value: "email" },
      { label: "Name", value: "name" },
    ],
    filters: [],
    mutations: { basePath: "/affiliates" },
    canCreate: true,
    canEdit: true,
    canDelete: true,
    canBulkDelete: false,
  },
  generations: {
    key: "generations",
    label: "Generations",
    labelSingular: "generation",
    description: "Generation request history, attribution, input parameters, and client metadata.",
    primaryKey: "id",
    defaultOrder: "created_at",
    defaultDescending: true,
    listDisplay: [
      { name: "type", label: "Type", kind: "status", sortable: true },
      { name: "prompt", label: "Prompt", sortable: true },
      {
        name: "user_id",
        label: "User",
        display: {
          primaryPath: "user.name",
          secondaryPath: "user.email",
          fallbackPaths: ["user.email", "user_id"],
        },
      },
      { name: "job_id", label: "Job", kind: "identifier", sortable: true },
      { name: "plan", label: "Plan", kind: "status", sortable: true },
      { name: "ip_address", label: "IP", kind: "identifier", sortable: true },
      { name: "created_at", label: "Created", kind: "date", sortable: true },
    ],
    fields: [
      { name: "title", label: "Title", kind: "text", nullable: true },
      { name: "user_id", label: "User ID", kind: "text", required: true, createOnly: true },
      { name: "api_key_id", label: "API key ID", kind: "text", nullable: true, createOnly: true },
      {
        name: "type",
        label: "Type",
        kind: "select",
        required: true,
        options: GENERATION_TYPE_OPTIONS,
        createOnly: true,
        defaultValue: "image",
      },
      { name: "prompt", label: "Prompt", kind: "textarea", required: true, createOnly: true },
      {
        createOnly: true,
        name: "params",
        label: "Parameters",
        kind: "json",
        jsonObject: true,
        nullable: true,
        defaultValue: {},
        help: "Valid JSON passed to the generation provider.",
      },
      { name: "job_id", label: "Job ID", kind: "text", nullable: true, createOnly: true },
      { name: "plan", label: "Plan snapshot", kind: "select", nullable: true, createOnly: true, options: PLAN_OPTIONS },
      { name: "ip_address", label: "IP address", kind: "text", nullable: true, createOnly: true },
      { name: "user_agent", label: "User agent", kind: "textarea", nullable: true, createOnly: true },
    ],
    searchFields: [
      { label: "Prompt", value: "prompt" },
      { label: "Job ID", value: "job_id" },
      { label: "Plan", value: "plan" },
    ],
    filters: [
      { name: "type", label: "Type", options: GENERATION_TYPE_OPTIONS },
      { name: "plan", label: "Plan", options: PLAN_OPTIONS },
    ],
    mutations: { basePath: "/generations" },
    canCreate: true,
    canEdit: true,
    canDelete: true,
    canBulkDelete: false,
  },
  priority_support_requests: {
    key: "priority_support_requests",
    label: "Priority support",
    labelSingular: "support ticket",
    description: "Enterprise priority support tickets and grievance reports.",
    primaryKey: "id",
    defaultOrder: "created_at",
    defaultDescending: true,
    listDisplay: [
      {
        name: "user_id",
        label: "User",
        display: {
          primaryPath: "user.name",
          secondaryPath: "user.email",
          fallbackPaths: ["user.email", "user_id"],
        },
      },
      { name: "user_plan", label: "User's Plan", kind: "status" },
      { name: "product", label: "Product" },
      {
        name: "generation_id",
        label: "Generation",
        kind: "link",
        linkPrefix: "/generations/",
      },
      { name: "status", label: "Status", kind: "status", sortable: true },
      { name: "created_at", label: "Created", kind: "date", sortable: true },
    ],
    fields: [
      { name: "user_id", label: "User ID", kind: "text", editOnly: true },
      { name: "user_email", label: "User Email", kind: "email", editOnly: true },
      { name: "user_plan", label: "User's Plan", kind: "text", editOnly: true },
      { name: "product", label: "Product", kind: "text", editOnly: true },
      { name: "api_key_id", label: "API key ID", kind: "text", nullable: true, editOnly: true },
      { name: "generation_id", label: "Generation ID", kind: "text", nullable: true, editOnly: true },
      { name: "greivience", label: "Grievance", kind: "textarea" },
      {
        name: "status",
        label: "Status",
        kind: "select",
        required: true,
        options: [
          { label: "Open", value: "open" },
          { label: "Resolved", value: "resolved" },
        ],
        defaultValue: "open",
      },
      { name: "created_at", label: "Created at", kind: "datetime", editOnly: true },
      { name: "updated_at", label: "Updated at", kind: "datetime", editOnly: true },
    ],
    searchFields: [
      { label: "User Email", value: "user_email" },
      { label: "User Name", value: "user_name" },
      { label: "Grievance", value: "greivience" },
      { label: "Generation ID", value: "generation_id" },
    ],
    filters: [
      {
        name: "status",
        label: "Status",
        options: [
          { label: "Open", value: "open" },
          { label: "Resolved", value: "resolved" },
        ],
      },
      {
        name: "product",
        label: "Product",
        options: [
          { label: "Image", value: "image" },
          { label: "Text to speech", value: "tts" },
          { label: "Video", value: "video" },
          { label: "Image to image", value: "image2image" },
        ],
      },
      {
        name: "user_id",
        label: "User ID",
      },
    ],
    mutations: { basePath: "/priority-support-requests" },
    canCreate: false,
    canEdit: true,
    canDelete: true,
    canBulkDelete: false,
  },
};

export const RESOURCE_KEYS = Object.keys(RESOURCE_CONFIGS) as ResourceKey[];

export const RESOURCE_SLUGS: Record<string, ResourceKey> = {
  "checkout-sessions": "checkout_sessions",
  "checkout-invites": "checkout_invites",
  "webhook-events": "webhook_events",
  "affiliate-commissions": "affiliate_commissions",
  "affiliate-withdrawals": "affiliate_withdrawals",
  "generation-attempts": "generation_attempts",
  "generation-outbox": "generation_outbox",

  products: "products",
  "product-routes": "product_routes",
  plans: "plans",
  subscriptions: "entitlements",
  "plan-limits": "plan_limits",
  users: "users",
  "api-keys": "api_keys",
  "security-blocklist": "security_blocklist",
  "meta-deletion-requests": "meta_deletion_requests",
  "newsletter-subscribers": "newsletter_subscribers",
  affiliates: "affiliates",
  generations: "generations",
  "priority-support": "priority_support_requests",
};

export const RESOURCE_ROUTE_SLUGS = Object.keys(RESOURCE_SLUGS);

export function isResourceKey(value: string): value is ResourceKey {
  return Object.prototype.hasOwnProperty.call(RESOURCE_CONFIGS, value);
}

export function resourceKeyFromSlug(value: string): ResourceKey | null {
  return RESOURCE_SLUGS[value] ?? (isResourceKey(value) ? value : null);
}

export function getResourceConfig(resource: ResourceKey): ResourceConfig {
  return RESOURCE_CONFIGS[resource];
}
