import type {
  ResourceConfig,
  ResourceField,
  ResourceKey,
  SelectOption,
} from "./types";

const PLAN_OPTIONS: SelectOption[] = [
  { label: "Free", value: "free" },
  { label: "Trial", value: "trial" },
  { label: "Pro", value: "pro" },
  { label: "Creator", value: "pro_plus" },
  { label: "Starter", value: "starter" },
  { label: "Scale", value: "scale" },
];

const GENERATION_TYPE_OPTIONS: SelectOption[] = [
  { label: "Image", value: "image" },
  { label: "Text to speech", value: "tts" },
  { label: "Video", value: "video" },
];

const USER_QUOTA_FIELDS: ResourceField[] = [
  {
    name: "daily_limit",
    label: "Daily limit",
    kind: "number",
    nullable: true,
    min: 0,
  },
  {
    name: "window_limit",
    label: "Rolling-window limit",
    kind: "number",
    nullable: true,
    min: 0,
  },
  {
    name: "max_concurrent",
    label: "Maximum concurrent jobs",
    kind: "number",
    nullable: true,
    min: 1,
  },
  {
    name: "image_daily_limit",
    label: "Image daily limit",
    kind: "number",
    nullable: true,
    min: 0,
  },
  {
    name: "tts_daily_limit",
    label: "TTS daily limit",
    kind: "number",
    nullable: true,
    min: 0,
  },
  {
    name: "video_daily_limit",
    label: "Video daily limit",
    kind: "number",
    nullable: true,
    min: 0,
  },
];

export const RESOURCE_CONFIGS: Record<ResourceKey, ResourceConfig> = {
  users: {
    key: "users",
    label: "Users",
    labelSingular: "user",
    description: "Accounts, plans, access state, and quota overrides.",
    primaryKey: "id",
    defaultOrder: "created_at",
    defaultDescending: true,
    listDisplay: [
      { name: "email", label: "Email", sortable: true },
      { name: "name", label: "Name", sortable: true },
      { name: "plan", label: "Plan", kind: "status", sortable: true },
      { name: "is_suspended", label: "Suspended", kind: "boolean", sortable: true },
      { name: "is_comped", label: "Comped", kind: "boolean", sortable: true },
      { name: "daily_used", label: "Daily used", kind: "number", sortable: true },
      { name: "daily_limit", label: "Daily limit", kind: "number", sortable: true },
      { name: "created_at", label: "Created", kind: "date", sortable: true },
    ],
    fields: [
      { name: "email", label: "Email", kind: "email", required: true },
      { name: "name", label: "Name", kind: "text", nullable: true },
      { name: "avatar_url", label: "Avatar URL", kind: "text", nullable: true },
      {
        name: "plan",
        label: "Plan",
        kind: "select",
        options: PLAN_OPTIONS,
        defaultValue: "free",
      },
      {
        name: "tier_override",
        label: "Tier override",
        kind: "select",
        nullable: true,
        options: [
          { label: "Admin", value: "admin" },
          { label: "Pro", value: "pro" },
          { label: "Trial", value: "trial" },
          { label: "Miscellaneous", value: "misc" },
        ],
      },
      {
        name: "is_comped",
        label: "Comped (non-paying)",
        kind: "boolean",
        defaultValue: false,
        help: "Required when an admin assigns a paid plan without a billing subscription.",
      },
      {
        name: "is_suspended",
        label: "Suspended",
        kind: "boolean",
        defaultValue: false,
      },
      {
        name: "referred_by",
        label: "Referral code",
        kind: "text",
        nullable: true,
      },
      ...USER_QUOTA_FIELDS,
    ],
    searchFields: [
      { label: "Email", value: "email" },
      { label: "Name", value: "name" },
      { label: "WorkOS ID", value: "workos_id" },
    ],
    filters: [
      { name: "plan", label: "Plan", options: PLAN_OPTIONS },
      {
        name: "is_suspended",
        label: "Suspended",
        options: [
          { label: "Yes", value: "true" },
          { label: "No", value: "false" },
        ],
      },
      {
        name: "is_comped",
        label: "Comped",
        options: [
          { label: "Yes", value: "true" },
          { label: "No", value: "false" },
        ],
      },
    ],
    mutations: { basePath: "/users" },
    canCreate: true,
    canEdit: true,
    canDelete: true,
    canBulkDelete: false,
  },
  api_keys: {
    key: "api_keys",
    label: "API keys",
    labelSingular: "API key",
    description: "Issue, scope, rename, revoke, and audit API credentials.",
    primaryKey: "id",
    defaultOrder: "created_at",
    defaultDescending: true,
    listDisplay: [
      { name: "key_hint", label: "Key", kind: "identifier", sortable: true },
      { name: "name", label: "Name", sortable: true },
      {
        name: "user_id",
        label: "User",
        display: {
          primaryPath: "user.name",
          secondaryPath: "user.email",
          fallbackPaths: ["user.email", "user_id"],
        },
      },
      { name: "type", label: "Type", kind: "status", sortable: true },
      { name: "is_active", label: "Active", kind: "boolean", sortable: true },
      { name: "calls_count", label: "Calls", kind: "number", sortable: true },
      { name: "last_used_at", label: "Last used", kind: "date", sortable: true },
      { name: "created_at", label: "Created", kind: "date", sortable: true },
    ],
    fields: [
      {
        name: "user_id",
        label: "User ID",
        kind: "text",
        required: true,
        createOnly: true,
        immutableOnEdit: true,
      },
      { name: "name", label: "Name", kind: "text", defaultValue: "Default Key" },
      {
        name: "type",
        label: "Type",
        kind: "select",
        required: true,
        immutableOnEdit: true,
        options: [
          { label: "Image generation", value: "image_gen" },
          { label: "Text to speech", value: "tts" },
          { label: "Video", value: "video" },
        ],
        defaultValue: "image_gen",
      },
      {
        name: "is_active",
        label: "Active",
        kind: "boolean",
        editOnly: true,
        defaultValue: true,
      },
    ],
    searchFields: [
      { label: "Key hint", value: "key_hint" },
      { label: "Name", value: "name" },
      { label: "Type", value: "type" },
    ],
    filters: [
      {
        name: "type",
        label: "Type",
        options: [
          { label: "Image generation", value: "image_gen" },
          { label: "Text to speech", value: "tts" },
          { label: "Video", value: "video" },
        ],
      },
      {
        name: "is_active",
        label: "Active",
        options: [
          { label: "Yes", value: "true" },
          { label: "No", value: "false" },
        ],
      },
    ],
    mutations: { basePath: "/api-keys" },
    canCreate: true,
    canEdit: true,
    canDelete: true,
    canBulkDelete: false,
    secretResponseFields: ["raw_key", "full_key"],
  },
  tier_defaults: {
    key: "tier_defaults",
    label: "Tier defaults",
    labelSingular: "tier default",
    description: "Default quotas applied to plans and optionally existing users.",
    primaryKey: "tier",
    defaultOrder: "updated_at",
    defaultDescending: true,
    listDisplay: [
      { name: "tier", label: "Tier", kind: "status", sortable: true },
      { name: "daily_limit", label: "Daily limit", kind: "number", sortable: true },
      { name: "window_limit", label: "Window limit", kind: "number", sortable: true },
      { name: "max_concurrent", label: "Concurrency", kind: "number", sortable: true },
      { name: "updated_by", label: "Updated by", sortable: true },
      { name: "updated_at", label: "Updated", kind: "date", sortable: true },
    ],
    fields: [
      {
        name: "tier",
        label: "Tier",
        kind: "select",
        required: true,
        immutableOnEdit: true,
        options: [
          { label: "Pro", value: "pro" },
          { label: "Creator", value: "pro_plus" },
          { label: "Trial", value: "trial" },
        ],
      },
      { name: "daily_limit", label: "Daily limit", kind: "number", required: true, min: 0 },
      { name: "window_limit", label: "Window limit", kind: "number", required: true, min: 0 },
      {
        name: "max_concurrent",
        label: "Maximum concurrent jobs",
        kind: "number",
        required: true,
        min: 1,
      },
      {
        name: "applyToExisting",
        label: "Apply to existing users",
        kind: "boolean",
        editOnly: true,
        defaultValue: false,
        help: "When limits change, also update users whose affected limits still match the previous defaults. Custom overrides are preserved.",
      },
    ],
    searchFields: [{ label: "Tier", value: "tier" }],
    filters: [
      {
        name: "tier",
        label: "Tier",
        options: [
          { label: "Pro", value: "pro" },
          { label: "Creator", value: "pro_plus" },
          { label: "Trial", value: "trial" },
        ],
      },
    ],
    mutations: { basePath: "/tier-defaults", updateMethod: "PUT" },
    canCreate: true,
    canEdit: true,
    canDelete: true,
    canBulkDelete: false,
  },
  security_blocklist: {
    key: "security_blocklist",
    label: "Security blocklist",
    labelSingular: "blocklist entry",
    description: "Denied IP addresses, CIDR ranges, and disposable email domains.",
    primaryKey: "id",
    defaultOrder: "created_at",
    defaultDescending: true,
    listDisplay: [
      { name: "type", label: "Type", kind: "status", sortable: true },
      { name: "value", label: "Value", kind: "identifier", sortable: true },
      { name: "reason", label: "Reason", sortable: true },
      { name: "created_by", label: "Created by", sortable: true },
      { name: "created_at", label: "Created", kind: "date", sortable: true },
    ],
    fields: [
      {
        name: "type",
        label: "Type",
        kind: "select",
        required: true,
        options: [
          { label: "IP address", value: "ip" },
          { label: "Email domain", value: "email_domain" },
        ],
        defaultValue: "ip",
        help: "Use IP for both individual IP addresses and CIDR ranges; the backend detects CIDR notation.",
      },
      { name: "value", label: "Value", kind: "text", required: true },
      { name: "reason", label: "Reason", kind: "textarea", nullable: true },
    ],
    searchFields: [
      { label: "Value", value: "value" },
      { label: "Reason", value: "reason" },
      { label: "Type", value: "type" },
    ],
    filters: [
      {
        name: "type",
        label: "Type",
        options: [
          { label: "IP address", value: "ip" },
          { label: "Email domain", value: "email_domain" },
        ],
      },
    ],
    mutations: { basePath: "/blocklist" },
    canCreate: true,
    canEdit: true,
    canDelete: true,
    canBulkDelete: true,
  },
  meta_deletion_requests: {
    key: "meta_deletion_requests",
    label: "Meta deletion requests",
    labelSingular: "Meta deletion request",
    description: "Track and resolve Meta data-deletion callbacks.",
    primaryKey: "id",
    defaultOrder: "requested_at",
    defaultDescending: true,
    listDisplay: [
      { name: "confirmation_code", label: "Confirmation", kind: "identifier", sortable: true },
      { name: "status", label: "Status", kind: "status", sortable: true },
      { name: "requested_at", label: "Requested", kind: "date", sortable: true },
      { name: "completed_at", label: "Completed", kind: "date", sortable: true },
      { name: "error", label: "Error", sortable: true },
    ],
    fields: [
      {
        name: "meta_user_id",
        label: "Meta user ID",
        kind: "text",
        required: true,
        createOnly: true,
        help: "Stored securely and intentionally omitted from table reads.",
      },
      {
        name: "confirmation_code",
        label: "Confirmation code",
        kind: "text",
        nullable: true,
        createOnly: true,
        help: "Leave empty to generate a code on the server.",
      },
      {
        name: "status",
        label: "Status",
        kind: "select",
        required: true,
        options: [
          { label: "Pending", value: "pending" },
          { label: "Processing", value: "processing" },
          { label: "Completed", value: "completed" },
          { label: "Failed", value: "failed" },
        ],
        defaultValue: "pending",
      },
      { name: "completed_at", label: "Completed at", kind: "datetime", nullable: true, editOnly: true },
      { name: "error", label: "Error", kind: "textarea", nullable: true, editOnly: true },
    ],
    searchFields: [
      { label: "Confirmation code", value: "confirmation_code" },
      { label: "Status", value: "status" },
    ],
    filters: [
      {
        name: "status",
        label: "Status",
        options: [
          { label: "Pending", value: "pending" },
          { label: "Processing", value: "processing" },
          { label: "Completed", value: "completed" },
          { label: "Failed", value: "failed" },
        ],
      },
    ],
    mutations: { basePath: "/meta-deletion-requests" },
    canCreate: true,
    canEdit: true,
    canDelete: true,
    canBulkDelete: false,
  },
  newsletter_subscribers: {
    key: "newsletter_subscribers",
    label: "Newsletter subscribers",
    labelSingular: "newsletter subscriber",
    description: "Email subscriptions and their acquisition source.",
    primaryKey: "id",
    defaultOrder: "created_at",
    defaultDescending: true,
    listDisplay: [
      { name: "email", label: "Email", sortable: true },
      { name: "source", label: "Source", kind: "status", sortable: true },
      { name: "created_at", label: "Subscribed", kind: "date", sortable: true },
    ],
    fields: [
      { name: "email", label: "Email", kind: "email", required: true },
      { name: "source", label: "Source", kind: "text", required: true, defaultValue: "admin" },
    ],
    searchFields: [
      { label: "Email", value: "email" },
      { label: "Source", value: "source" },
    ],
    filters: [{ name: "source", label: "Source" }],
    mutations: { basePath: "/newsletter-subscribers" },
    canCreate: true,
    canEdit: true,
    canDelete: true,
    canBulkDelete: true,
  },
  affiliates: {
    key: "affiliates",
    label: "Affiliates",
    labelSingular: "affiliate",
    description: "Referral partners, contact details, and available wallet balance.",
    primaryKey: "id",
    defaultOrder: "created_at",
    defaultDescending: true,
    listDisplay: [
      { name: "email", label: "Email", sortable: true },
      { name: "name", label: "Name", sortable: true },
      { name: "wallet_balance", label: "Wallet (USD)", kind: "number", sortable: true },
      { name: "created_at", label: "Joined", kind: "date", sortable: true },
    ],
    fields: [
      { name: "email", label: "Email", kind: "email", required: true },
      { name: "name", label: "Name", kind: "text", nullable: true },
      {
        name: "wallet_balance",
        label: "Wallet balance (USD)",
        kind: "number",
        min: 0,
        step: 0.01,
        defaultValue: 0,
        help: "Manual changes affect the payout balance; verify them against the commission ledger.",
      },
    ],
    searchFields: [
      { label: "Email", value: "email" },
      { label: "Name", value: "name" },
    ],
    filters: [],
    mutations: { basePath: "/affiliates" },
    canCreate: true,
    canEdit: true,
    canDelete: true,
    canBulkDelete: false,
  },
  generations: {
    key: "generations",
    label: "Generations",
    labelSingular: "generation",
    description: "Generation request history, attribution, input parameters, and client metadata.",
    primaryKey: "id",
    defaultOrder: "created_at",
    defaultDescending: true,
    listDisplay: [
      { name: "type", label: "Type", kind: "status", sortable: true },
      { name: "prompt", label: "Prompt", sortable: true },
      {
        name: "user_id",
        label: "User",
        display: {
          primaryPath: "user.name",
          secondaryPath: "user.email",
          fallbackPaths: ["user.email", "user_id"],
        },
      },
      { name: "job_id", label: "Job", kind: "identifier", sortable: true },
      { name: "plan", label: "Plan", kind: "status", sortable: true },
      { name: "ip_address", label: "IP", kind: "identifier", sortable: true },
      { name: "created_at", label: "Created", kind: "date", sortable: true },
    ],
    fields: [
      { name: "user_id", label: "User ID", kind: "text", required: true },
      { name: "api_key_id", label: "API key ID", kind: "text", nullable: true },
      {
        name: "type",
        label: "Type",
        kind: "select",
        required: true,
        options: GENERATION_TYPE_OPTIONS,
        defaultValue: "image",
      },
      { name: "prompt", label: "Prompt", kind: "textarea", required: true },
      {
        name: "params",
        label: "Parameters",
        kind: "json",
        jsonObject: true,
        nullable: true,
        defaultValue: {},
        help: "Valid JSON passed to the generation provider.",
      },
      { name: "job_id", label: "Job ID", kind: "text", nullable: true },
      { name: "plan", label: "Plan snapshot", kind: "select", nullable: true, options: PLAN_OPTIONS },
      { name: "ip_address", label: "IP address", kind: "text", nullable: true },
      { name: "user_agent", label: "User agent", kind: "textarea", nullable: true },
    ],
    searchFields: [
      { label: "Prompt", value: "prompt" },
      { label: "Job ID", value: "job_id" },
      { label: "Plan", value: "plan" },
    ],
    filters: [
      { name: "type", label: "Type", options: GENERATION_TYPE_OPTIONS },
      { name: "plan", label: "Plan", options: PLAN_OPTIONS },
    ],
    mutations: { basePath: "/generations" },
    canCreate: true,
    canEdit: true,
    canDelete: true,
    canBulkDelete: false,
  },
};

export const RESOURCE_KEYS = Object.keys(RESOURCE_CONFIGS) as ResourceKey[];

export const RESOURCE_SLUGS: Record<string, ResourceKey> = {
  users: "users",
  "api-keys": "api_keys",
  "tier-defaults": "tier_defaults",
  "security-blocklist": "security_blocklist",
  "meta-deletion-requests": "meta_deletion_requests",
  "newsletter-subscribers": "newsletter_subscribers",
  affiliates: "affiliates",
  generations: "generations",
};

export const RESOURCE_ROUTE_SLUGS = Object.keys(RESOURCE_SLUGS);

export function isResourceKey(value: string): value is ResourceKey {
  return Object.prototype.hasOwnProperty.call(RESOURCE_CONFIGS, value);
}

export function resourceKeyFromSlug(value: string): ResourceKey | null {
  return RESOURCE_SLUGS[value] ?? (isResourceKey(value) ? value : null);
}

export function getResourceConfig(resource: ResourceKey): ResourceConfig {
  return RESOURCE_CONFIGS[resource];
}
